<a href="https://colab.research.google.com/github/PraphulKamabathula/DS1002-qtm3tc/blob/main/homework/week-6.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework - Week 6

Complete the following blocks as specified in the directions. Run each cell to return the desired output. Save your notebook back to your GitHub repository and submit the GitHub URL for your notebook for review.

# Pandas

## 1. Fetch and Load Data
In class we created a DataFrame using the `read_csv` method. Go to https://catalog.data.gov/dataset/electric-vehicle-population-data and download the CSV format of the "Electric Vehicle Population Data" dataset. Then upload it to Google Colab.

Load that data into a Pandas DataFrame and display the first 20 rows. Show your work.

In [46]:
# Set up pandas and populate the dataframe above using the raw data. Then continue to work with the dataframe in the questions below.
import pandas as pd
import numpy as np
EVPop = pd.read_csv('Electric_Vehicle_Population_Data.csv')

In [10]:
# Format a command that how many rows and columns are in this dataset.
EVPop.shape

(150482, 17)

In [30]:
# Format a command that displays every other row of records 1000 through 1999, and the columns "City", "State", "Model Year", and "Make".
EVPop.loc[1001:2000:2, ["City","State","Model Year","Make"]]

           City State  Model Year      Make
1001       Kent    WA        2018     TESLA
1003  Newcastle    WA        2022     TESLA
1005   Kirkland    WA        2015     TESLA
1007   Issaquah    WA        2016    NISSAN
1009       Kent    WA        2023     TESLA
...         ...   ...         ...       ...
1991   Kirkland    WA        2018  CHRYSLER
1993   Bellevue    WA        2014     TESLA
1995       Kent    WA        2023   HYUNDAI
1997  Vancouver    WA        2017    TOYOTA
1999     Seatac    WA        2022     TESLA

[500 rows x 4 columns]

# 2. Cleaning/Imputing Data

In class we reviewed methods for removing duplicate rows and handling empty cell values. Download [this data set](https://github.com/nmagee/ds1002/blob/main/data/very-messy-data.csv) and upload into Google Colab.

Create another Pandas DataFrame from that data and perform the following steps.

In [41]:
# Set up pandas and populate the dataframe above using the raw data. Then continue to work with the dataframe in the questions below.
flowers = pd.read_csv("very-messy-data (1).csv")

In [32]:
# Write a snippet of code that will display the number of duplicate rows exist in the DF.
flowers.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1311     True
1312     True
1313     True
1314     True
1315     True
Length: 1316, dtype: bool

In [34]:
# Next, remove all duplicate rows using Python.
flowers = flowers.drop_duplicates()
print(flowers)

       id  sepal_length  sepal_width  petal_length  petal_width    species
0       1           3.5          2.9           1.4          0.5  virginica
1       2           3.6          3.2           3.0          0.5     setosa
2       3           3.8          NaN           2.2          1.5     setosa
3       4           5.8          2.7           2.6          1.2  virginica
4       5           4.9          3.6           3.0          1.2  virginica
..    ...           ...          ...           ...          ...        ...
995   996           4.5          3.6           NaN          2.7     setosa
996   997           4.0          2.1           NaN          2.1     setosa
997   998           5.9          2.5           2.1          2.5  virginica
998   999           5.0          2.6           1.9          NaN        NaN
999  1000           3.4          3.9           1.9          1.5     setosa

[1000 rows x 6 columns]

In [51]:
# For the FOUR columns involving sepal and petal length and width, update all NaN
# values with the column mean such that NO empty cells remain. This method
# is called "imputation" because it fills in cells in a statistically less-impactful
# way than if they were blank.

# Show how you would update those four columns in code

flowers_filled = flowers.fillna(flowers.median())

flowers_filled

<ipython-input-51-4cd89429da22>:8: FutureWarning: The default value of numeric_only in DataFrame.median is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  flowers_filled = flowers.fillna(flowers.median())

       id  sepal_length  sepal_width  petal_length  petal_width    species
0       1           3.5          2.9           1.4          0.5  virginica
1       2           3.6          3.2           3.0          0.5     setosa
2       3           3.8          3.0           2.2          1.5     setosa
3       4           5.8          2.7           2.6          1.2  virginica
4       5           4.9          3.6           3.0          1.2  virginica
...   ...           ...          ...           ...          ...        ...
1311  412           4.6          3.6           2.9          0.5  virginica
1312  413           5.8          2.7           2.0          0.1  virginica
1313  414           3.3          3.7           1.3          2.8     setosa
1314  415           3.1          3.0           1.1          1.6  virginica
1315  416           4.3          2.5           1.3          1.0     setosa

[1316 rows x 6 columns]

# 3. Save to a New CSV

Preserve your updated DF to a CSV file by using the method built into Pandas.
Name the output file `very-clean-data.csv` and save it to GitHub in the same directory where you will save this homework. We will review both your Colab notebook and the cleaned data file.

In [52]:
flowers_filled.to_csv("very-clean-data.csv")